

messages:
  incoming:
    select: [player, obj_id]
    info: [player, obj_id]
    play_card: [player, obj_id]
    save: [player]

  outgoing:
    create: [obj_id, type, properties]
    destroy: [obj_id, type, properties]
    move: [obj_id, pos] # same as destroy + create copy
    stat: [] # for victory points
    message: [content]

asset_types: # and properties
  border:
    obj_id: --int--
    type: [Plains, Forest, Mountains, Coast, Strait, Ocean]
  tile:
    obj_id: --int--
    type: [Land, Sea, Ocean]
    owner: --nations--
  unit:
    obj_id: --int--
    tile: --tiles--
    type: --unit_types--
    owner: [Britain, France, USA, Germany, Italy, USSR, Independent]
    cv: --int--
  action_card:
    obj_id: --int--
    name: --str--
    faction: [West, Axis, USSR]
    wildcard: -- list of wild cards --
    played: [true, false]
    top_technology: --independent nations--
    bottom_technology: --independent nations--
    command_value: --int--
    command_priority: --letter--
  investment_card:
    obj_id: --int--
    name: --str--
    faction: [West, Axis, USSR]
    intelligence: --espionage--
    played: [true, false]
    factory_value: --int--
    top_technology: --technologies--
    bottom_technology: --technologies--
    science_year: --int--
    science_techs: --list of techs--
  influence:
    obj_id: --int--
    faction: [West, Axis, USSR]
    nation: --independent nations--


