Axis:
    members:
        Germany:
            type: Great Power
            HomeCapital: Berlin
            SubCapitals: [Ruhr]
        Italy:
            type: Major Power
            HomeCapital: Rome
            Colonies: [Lybia]
    
    MainCapital: Berlin
    SubCapitals: [Ruhr, Rome]

    setup:
        action_cards: 14
        cadres:
            Germany:
                Berlin: 6
                Ruhr: 4
                Munich: 2
                Konigsberg: 2
            Italy:
                Rome: 4
                Milan: 2
                Tripoli: 2
    
    unit_count:
        Germany:
            Infantry: 16
            Fortress: 8
            Tank: 8
            AirForce: 8
            Fleet: 6
            Carrier: 2
            Submarine: 8
        Italy:
            Infantry: 6
            Fortress: 2
            Tank: 2
            AirForce: 3
            Fleet: 4
            Carrier: 1
            Submarine: 2
        
USSR:
    members:
        USSR:
            type: Great Power
            HomeCapital: Moscow
            SubCaptials: [Leningrad, Baku]
    
    MainCapital: Moscow
    SubCapitals: [Leningrad, Baku]

    setup:
        action_cards: 6
        units:
            USSR:
                tile: Moscow
                type: Infantry
                cv: 3
        cadres:
            USSR:
                Moscow: 3
                Leningrad: 2
                Baku: 2
                Kiev: 1
                Kharkov: 1
                Odessa: 1
                Stalingrad: 1
                Urals: 1
    
    unit_count:
        USSR:
            Infantry: 16
            Fortress: 6
            Tank: 8
            AirForce: 6
            Fleet: 4
            Carrier: 2
            Submarine: 2

West:
    members:
        Britain:
            type: Great Power
            HomeCapital: London
            SubCapitals: [Delhi]
            Colonies: [Canada, Gibraltar, Malta, Middle East, India]
        France:
            type: Major Power
            HomeCapital: Paris
            Colonies: [French North Africa, Syria]
        USA:
            type: Major Power
            HomeCapital: Washington

    MainCapital: London
    SubCapitals: [Delhi, Paris, Washington]

    setup:
        action_cards: 8
        units:
            Britain:
                tile: London
                type: Fleet
                cv: 4
            France:
                tile: Lorraine
                type: Fortress
                cv: 3
        cadres:
            Britain:
                London: 3
                Delhi: 2
                Glasgow: 1
                Bombay: 1
                Suez: 1
            France:
                Paris: 2
                Marseilles: 1
                Algiers: 1
    
    unit_count:
        Britain:
            Infantry: 6
            Fortress: 6
            Tank: 3
            AirForce: 4
            Fleet: 6
            Carrier: 2
            Submarine: 3
        France:
            Infantry: 6
            Fortress: 3
            Tank: 2
            AirForce: 3
            Fleet: 4
            Carrier: 1
            Submarine: 1
        USA:
            Infantry: 4
            Fortress: 2
            Tank: 4
            AirForce: 4
            Fleet: 4
            Carrier: 1
            Submarine: 1
